[package]
name = "transform-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[features]
default = []
wasi = ["dep:wasmtime-wasi"]

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
common = { path = "../common" }
dashmap = "6.1.0"
futures = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
wasmtime = { version = "24.0.6", default-features = false, features = ["cranelift", "runtime"] }
wasmtime-wasi = { version = "24.0.6", optional = true }
async-stream = "0.3"
