[package]
name = "protocol-nvme"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[features]
default = []
phase4 = ["common/podms", "scaling/phase4"]

[dependencies]
anyhow = { workspace = true }
capsule-registry = { path = "../capsule-registry", features = ["phase4"] }
common = { path = "../common" }
scaling = { path = "../scaling", features = ["phase4"] }
spdk-rs = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
encryption = { path = "../encryption" }
nvram-sim = { path = "../nvram-sim" }
