[package]
name = "sim-nvmeof"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "sim-nvmeof"
path = "src/bin/main.rs"

[dependencies]
anyhow.workspace = true
byteorder = "1.4"
tracing.workspace = true
tracing-subscriber.workspace = true
spdk-rs = { path = "../../vendor/spdk-rs", optional = true }
libc = { version = "0.2", optional = true }

[dev-dependencies]
tracing-test.workspace = true

[features]
default = []
spdk = ["dep:spdk-rs", "dep:libc"]
