[package]
name = "federation"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[features]
default = []
phase4 = []

[dependencies]
anyhow = { workspace = true }
blake3 = { workspace = true }
bincode = { workspace = true }
capsule-registry = { path = "../capsule-registry", default-features = false }
common = { path = "../common" }
nvram-sim = { path = "../nvram-sim" }
prost = "0.13.5"
serde = { workspace = true }
serde_json = { workspace = true }
sled = "0.34"
tokio = { workspace = true, features = ["rt", "sync", "macros", "time"] }
tokio-stream = { version = "0.1.17", features = ["net"] }
tonic = { version = "0.12.3", features = ["transport"] }
tracing = { workspace = true }
raft = { version = "0.7.0", default-features = false, features = ["prost-codec", "default-logger"] }
slog = "2"
slog-stdlog = "4"

[dev-dependencies]
tempfile = "3"
tracing-subscriber = { workspace = true }

[build-dependencies]
tonic-build = "0.12.3"
protoc-bin-vendored = "3.2.0"
