[package]
name = "pipeline"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[features]
default = []
phase5 = ["dep:transform-engine"]

[dependencies]
anyhow = { workspace = true }
common = { path = "../common" }
layout-engine = { path = "../layout-engine" }
compression = { path = "../compression" }
dedup = { path = "../dedup" }
storage = { path = "../storage" }
encryption = { path = "../encryption" }
transform-engine = { path = "../transform-engine", optional = true }
futures = { workspace = true }
tracing = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
tokio-util = { version = "^0.7.18", features = ["io"] }
bytes = { workspace = true }
async-stream = "0.3"
uuid = { workspace = true }

[dev-dependencies]
tempfile = "3"
