name: 🐛 Bug Report
description: File a bug report
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: Clear & concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: Steps to reproduce.
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      value: "main"
