name: ✨ Feature Request
description: Suggest an idea
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
