name: Feature Request
description: Suggest an idea for SPACE
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
    validations:
      required: true
