[package]
name = "space-fuzz"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []
fuzzing = []

[dependencies]
anyhow = "1"
libfuzzer-sys = "0.4"

[package.metadata]
cargo-fuzz = true

[dependencies.common]
path = "../crates/common"
default-features = true

[dependencies.encryption]
path = "../crates/encryption"
default-features = true

[dependencies.layout-engine]
path = "../crates/layout-engine"
default-features = true

[[bin]]
name = "encrypt_roundtrip"
path = "fuzz_targets/encrypt_roundtrip.rs"
test = false
doc = false
required-features = ["fuzzing"]

[[bin]]
name = "policy_fuzz"
path = "fuzz_targets/policy_fuzz.rs"
test = false
doc = false
required-features = ["fuzzing"]
