apiVersion: v1
kind: ConfigMap
metadata:
  name: phase4-policy
  namespace: default
data:
  phase4-policy.yaml: |
    compression:
      LZ4:
        level: 1
    dedupe: true
    compact_interval_secs: 600
    encryption:
      XtsAes256:
        key_version: null
    crypto_profile: Classical
    rpo:
      secs: 0
      nanos: 0
    sovereignty: zone
    view: csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacectl-csi-driver
  labels:
    app: spacectl-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacectl-csi
  template:
    metadata:
      labels:
        app: spacectl-csi
    spec:
      containers:
        - name: spacectl
          image: saworbit/spacectl:phase4
          imagePullPolicy: IfNotPresent
          command: ["spacectl"]
          args:
            - project
            - --view
            - csi
            - --id
            - 550e8400-e29b-41d4-a716-446655440000
            - --policy-file
            - /etc/space/phase4-policy.yaml
          volumeMounts:
            - name: policy
              mountPath: /etc/space
      volumes:
        - name: policy
          configMap:
            name: phase4-policy
